services:
  - type: web
    name: smart-campus-backend
    env: docker
    plan: free
    envVars:
      - key: JAVA_VERSION
        value: 21
      - key: EMAIL_PASSWORD
        sync: false
      # Production database variables
      - key: DB_URL
        value: ${DATABASE_URL}
      - key: DB_USERNAME
        value: ${DATABASE_USERNAME}
      - key: DB_PASSWORD
        value: ${DATABASE_PASSWORD}
databases:
  - name: smart-campus-db
    plan: free
